### ISSUE TITLE
Logging in when the NAMELIST has been used up may get username 'visitor'

### ISSUE THREAD

**Issue by yangl1996** [yangl1996/mini-chatter#12]
测试时不小心用完了服务器的NAMELIST，再登陆时发现抽到了visitor用户名。（此时登陆可能抽到visitor、水表、顺风三种）

**Comment by Jueast** [comment]
Are you sure about the name is "vistor" ,not "Visitor"?

**Comment by yangl1996** [comment]
Mistake! It is 'Visitor'.

**Comment by Jueast** [comment]
I catched the bug in #18  

Could you help me test the code in your localhost?

I have to do my part-job now  : > @yangl1996

**Comment by yangl1996** [comment]
@Jueast the bug no longer exists :)
