### ISSUE TITLE
Unexpected message appear from vistor in logging

### ISSUE THREAD

**Issue by Jueast** [yangl1996/mini-chatter#8]
当某种情况下login时, 会自行发出奇怪消息:"GET HTTP ...."

需要测试

和主机部署环境有关

**Comment by yangl1996** [comment]
今晚使用时发现，一段时间静置就会产生这个情况：
![issue](https://cloud.githubusercontent.com/assets/1909857/6129445/9033c132-b179-11e4-8c52-93092865f0b2.png)
正在尝试重现bug并且通过抓包分析

**Comment by yangl1996** [comment]
基本确定是主机环境有关。Host: kiwiproxychecker.sioru.com一行可以看出。Kiwi是VPS使用的后台管理面板，proxychecker应该是用于检测这是不是公共代理（违反term of service）。访问sioru.com，发现跳转到it7.net，也就是VPS提供商。

**Comment by Jueast** [comment]
也许可以通过添加 /message 来控制 无关信息?

**Comment by Jueast** [comment]
同时可以和加密系统整合避免telnet等直连

**Comment by yangl1996** [comment]
有道理> < 信息之前还是应该添加一些特征，由客户端检测

**Comment by Jueast** [comment]
这样同时可以处理掉 输入框打命令的异常...因为前面加了/message 就成了普通文本
server已经处理了. 9ae7ebfbd986ddd274b70c428a153ba4273e09ae
